### ISSUE TITLE
Feature gap vs. RestKit mapping

### ISSUE THREAD

**Issue by sixten** [lucasmedeirosleite/EasyMapping#110]
I've been looking for a replacement for RestKit for mapping JSON data to managed objects in our apps, and came across EasyMapping recently. I've been poking around in the documentation and the code, and starting up some pilot efforts to port over some existing code. There are a few things that I've run across that we're doing with RestKit that EasyMapping doesn't seem to support, and I wanted to ask 1) whether there are other ways of accomplishing those goals that I'm missing, and 2) whether you'd have any interest in adding those features. I don't want to just fork the code and start hacking on it for our purposes if I can usefully contribute to the project itself!

# "Magic" keys and metadata

RestKit [implements a couple of "magic" keys](http://cocoadocs.org/docsets/RestKit/0.25.0/Classes/RKMappingOperation.html) for its key-value mapping. We don't make extensive use of them, but where we do, there doesn't seem to be a way to accomplish the same thing with EasyMapping:

## `@parent`

This key allows a child object mapping access values from its containing parent object. The main place we use this is with JSON that doesn't have parent IDs on child objects, but where the managed objects need those values. For example:

    { "objectID": 1,
      "parts" : [
        { "partID": 1,
          "type" : "widget"
        }
      ]
    }

In the Core Data model, the `Part` has an `objectID` property, but that value's not directly included in the representation. It's implicit, in that each part comes contained in a parent object, though, so with RestKit we can define a mapping from the key path `@parent.objectID` to the `objectID` property.

Another way to accomplish the goal (and probably simpler to implement?) would be if the relationship mapping had some way of gathering some "extra" information to carry along with it. There's a somewhat similar mechanism in EasyMapping with `nonNestedKeyPaths`, but that's only for to-one relationships.

## `@metadata`

This key allows access to some other information associated with the mapping process:

  * Code that initiates a mapping process can specify explicit metadata that is then accessible from mappings. We use this in a couple of places where we are requesting specific objects from an API, but the response doesn't include their keys.
  
  * There is also some implicit metadata generated by the mapping process itself. One very useful value that is `@metadata.mapping.collectionIndex`, which evaluates to the index of the source representation within a JSON array. We use it in several places for assigning sort order values mapped objects. I'm not sure how we could accomplish that with EasyMapping.
  
## `@root`

I'll mention this key for the sake of completeness, but we're not currently using it anywhere. It points to the top-level JSON object involved in the mapping.

# Relationship assignment policy

When updating the value of a to-many relationship, RestKit provides three possible [assignment policy](http://cocoadocs.org/docsets/RestKit/0.25.0/Classes/RKRelationshipMapping.html) values. These seem to fill a similar role to EasyMapping's `incrementalData` property, but they don't line up 100%. Specifically, `RKReplaceAssignmentPolicy`, which replaces the value of the relationship, and then deletes any objects that were just disconnected, enabling the garbage collection of orphaned objects. (In the case of a mandatory parent-child relationship, such orphans would cause validation errors preventing the context from saving.)

# Identification attributes

EasyMapping supports finding and matching managed objects based on a single primary key property. RestKit defaults to that, but allows for entity mappings based on multiple [`identificationAttributes`](http://cocoadocs.org/docsets/RestKit/0.25.0/Classes/RKEntityMapping.html#//api/name/identificationAttributes).

Looking at the way that we're using this code in our apps, though, where we're using this in practice, it's generally to scope keys that are not globally unique. For example, we might have an `Object` containing `Part`s, where each one has a `partID` (specific to that `Object`) and an `objectID` (globally unique).

    { "objects": [
        { "objectID": 1,
          "parts" : [
            { "partID": 1,  // *** this part has the same ID...
              "objectID" : 1,
              "type" : "widget"
            }
          ]
        },
        { "objectID": 2,
          "parts" : [
            { "partID": 1,  // *** ...as this part, but different parent object
              "objectID" : 2,
              "type" : "sprocket"
            }
          ]
        }
      ]
    }

It seems to me that, rather than trying to match objects based on multiple properties, we might be able to accomplish the same thing by defining a predicate on the relationship to restrict its scope. In this example, `Object` has a to-many relationship to `Part`, `Part` has a single primary key of `partID`, and the relationship restricts the set of parts to those where `objectID == %@`. (The mapper would need to fill in the specific value from each `Object`.)

# Deletion predicates

`RKEntityMapping` provides a [`deletionPredicate`](http://cocoadocs.org/docsets/RestKit/0.25.0/Classes/RKEntityMapping.html#//api/name/deletionPredicate) property for cleaning up the stored data, once mapping is complete. RestKit will run a fetch request against the mapping's entity with that predicate, and delete any objects that it finds. (For example, removing records that have been marked inactive, or have reached some expiration date.)

This feature probably has the weakest case for inclusion in EasyMapping. It's convenient, for sure, but that responsibility could also be pushed back to whatever process is running the mapping. The major advantage to keeping it with the mapping definitions is that, in complex scenarios, there might be a lot of entity types involved, and higher-level code shouldn't have to know about all of them.

**Comment by DenHeadless** [comment]
Hi, @sixten!

Thank you for such detailed write-up on RestKit vs EasyMapping API. I think we definitely want some of this stuff to be implemented, because they allow more flexibility in mapping process. Right now i don't have time to implement these features myself, as i'm busy on different open-source projects, however i will be happy to provide feedback and discuss any new features with you if you would like to take a stab on implementing them.

I'd say most important of these are "magic" keys - **parent and metadata** - i've seen some requests, that could be resolved using those.

**Relationship assignment policy** is also good to have - we have several features in EasyMapping to support this kind of behaviour or similiar to this, and i think we can make a better job of unifying this feature. We already have `incrementalData` property and syncArrayOfObjectsFromExternalRepresentation: on EKManagedObjectMapper. Those could be unified in assignment policies.

As for identification attributes and deletion predicates, i don't think those are high priority features, i think we need to pass on deletion predicates completely, as it's such a niche feature, that does not actually need to be present in a framework. We need to remain "Easy" =)

**Comment by sixten** [comment]
I assumed that not all of these would be relevant to the core project, so that's totally fine. And I assumed that I'd be doing much of the work, but I would definitely be interested in adding stuff in a way that harmonizes with the existing project.

> I'd say most important of these are "magic" keys - parent and metadata - i've seen some requests, that could be resolved using those.

Do you have a sense for whether you'd want these handled as magic keys, or in some other way? RestKit's approach is kind of clever, and it allows adding some mapping features without additional API surface, but it also means having to get into the business of parsing the key paths defined in the mappings, which is a little messy. I haven't thought deeply about this, but it seems like a more explicit mechanism to carry data down into subsequent mappings might be cleaner.

> Those could be unified in assignment policies.

Interesting point about using this to also cover the distinction between the "map" and "sync" operations. I hadn't really thought about that.

**Comment by DenHeadless** [comment]
> Do you have a sense for whether you'd want these handled as magic keys, or in some other way? 

This seems like something that could be resolved on EKMapper level or EKRelationshipMapping level. Maybe we should make EKRelationshipMapping class public API and return it from every map: operation. This way user could set some additional properties on it, for example for retrieving metadata. 

Another way of implementing this would be to have EKMapper delegate that can react to various mapping events.

However, it's just a thoughts, i actually have no idea how this should work.

**Comment by donpeter06** [comment]
Is it possible to access the root Json object using @root if the key-path is empty.

**Comment by DenHeadless** [comment]
Closing this issue for now.
