### ISSUE TITLE
reverse mapping of date not working

### ISSUE THREAD

**Issue by szehnder** [lucasmedeirosleite/EasyMapping#117]
using v. 0.15.3, neither of the following mappings seem to work when using EKSerializer to create NSDictionary from an entity:

```Swift
        mapping.mapKeyPath("timestamp", toProperty: "evvTimestamp", withValueBlock: { (str:String!, obj:AnyObject!, context:NSManagedObjectContext!) -> AnyObject! in
                return NSDateFormatter.isoFormatter().dateFromString(str)
        }) { (obj:AnyObject!, context:NSManagedObjectContext!) -> AnyObject! in
            let str = NSDateFormatter.isoFormatter().stringFromDate(obj as! NSDate) as String
            return str
        }
```
I've also tried the following:
```Swift
mapping.mapKeyPath("timestamp", toProperty:"evvTimestamp", withDateFormatter: NSDateFormatter.isoFormatter())
```
That formatter looks like so:
```Swift
extension NSDateFormatter {
    
    class func isoFormatter() -> NSDateFormatter {
        let formatter = NSDateFormatter()
        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZ"
        return formatter
    }
}
```

Here's how I'm trying to serialize it:
```Swift
        var payload = EKSerializer.serializeObject(request, withMapping: mapping)
```
When I do so, I am getting the following runtime error when converting my NSDictionary to JSON:
'Invalid type in JSON write (__NSDate)'

this would indicate to me that the item is still an NSDate and not a string, as I would have expected.

**Comment by DenHeadless** [comment]
Can i ask you to provide example project or a test for this issue? 

It is possible this is Swift-Objective-C interoperability issue.

**Comment by Ganon-M** [comment]
I think I might have a solution to this issue. I had the exact same problem with the EKSerializer not correctly converting the NSDate to a NSString. The issue was that I was calling the incorrect serialization method. Like you, I was using an NSManagedObject and attempting this

```objective-c
  NSDictionary *eventDictionary =
      [EKSerializer serializeObject:event
                        withMapping:[DMEAEvent objectMapping]];
````

Instead, what you want to call is this method (passing in a suitable NSManagedObjectContext)

```objective-c
 NSDictionary *eventDictionary = [EKSerializer
      serializeObject:event
          withMapping:[DMEAEvent objectMapping]
          fromContext:
              [[DMEAPersistenceManager sharedInstance] managedObjectContext]];
```
Once I did this, the NSDates were correctly serialized. For reference, here is part of my EKManagedObjectMapping implementation
```objective-c
[mapping mapPropertiesFromArray:
          @[ @"name", @"owner", @"members", @"uuid" ]];
NSDateFormatter *dateFormatter =
 [NSDateFormatter ek_formatterForCurrentThread];
[mapping mapKeyPath:@"creationDate"
        toProperty:@"creationDate"
 withDateFormatter:dateFormatter];
[mapping mapKeyPath:@"date"
        toProperty:@"date"
 withDateFormatter:dateFormatter];
```
Hope this helps someone.
