### ISSUE TITLE
ignoreMissingFields does not work in case of ValueBlock parsing

### ISSUE THREAD

**Issue by VladNaimark** [lucasmedeirosleite/EasyMapping#126]
It seems that mapKeyPath: toProperty: withValueBlock: is called when ignoreMissingFields set to YES and keyPath is missing from representation.
To fix it you should either pass EKObjectMapping and check it's ignoreMissingFields inside getValueOfProperty: fromRepresentation: of EKPropertyHelper or make EKPropertyMapping know it's objectMapping.
I'd fix it myself, but dunno which way is better

**Comment by DenHeadless** [comment]
Fixed, thanks for reporting! When ignoreMissingFields property is turned on, value block will no longer be called.
