### ISSUE TITLE
add support for different relationship assignment policies for when mapping managed objects 

### ISSUE THREAD

**Issue by adrian-gierakowski** [lucasmedeirosleite/EasyMapping#128]
as implemented in FastEasyMapping:
https://github.com/Yalantis/FastEasyMapping#assignment-policy

this is a really useful feature ( actually a must for my needs ), I had a quick look at your source and it seems like this future is not available in EasyMapping ( please correct me if I am wrong )

I am currently using Mantle, which I forked to add merge\overwrite policies for to-many relationships, however I have recently hit the performance problems, which were pointed out by authors of FastEasyMapping, and am thinking of switching to EasyMapping.

Would adding this feature be of interest to authors of EasyMapping?

Btw, the following would also be awesome to have:
https://github.com/Yalantis/FastEasyMapping#relationship-bindings-by-pk

thanks for the great work!

**Comment by DenHeadless** [comment]
Those would be nice to have.

PR's would be super nice!

**Comment by DenTelezhkin** [comment]
This issue is stale, if you want to pursue this functionality with EasyMapping, pull request is greatly appreciated.

Closing issue for now.
