### ISSUE TITLE
Xcode 7.3 complain "Include of non-modular header inside framework"

### ISSUE THREAD

**Issue by niyazahmed** [lucasmedeirosleite/EasyMapping#135]
I'm trying to include #import <EasyMapping/EasyMapping.h> into my class in a Target not on the main app. This class is also being used by some swift classes. I am getting this error "Include of non-modular header inside framework" I am basically stuck. not able to get over this. I use cocoapods to install EasyMapping in my target.

I do something like this.
target TARGET_NAME, :exclusive => true do
    pod 'EasyMapping', '0.17.0'
end

**Comment by DenHeadless** [comment]
Can i ask you to try installing EasyMapping from master branch? I added angular brackets for framework imports, this can potentially fix the issue.

Also, please post Xcode and CocoaPods versions you are using, as well as code, which gets compile errors.

**Comment by DenHeadless** [comment]
This looks stale, closing.
