### ISSUE TITLE
EasyMapping does not map one-to-many relationship for Core Data

### ISSUE THREAD

**Issue by Chernomor1984** [lucasmedeirosleite/EasyMapping#136]
Hey, guys!
Many thanks to you for this brilliant mapping lib)

The problem is briefly described here 
[http://stackoverflow.com/questions/38236056/easymapping-does-not-map-one-to-many-relationship-for-core-data](url)

**Comment by DenHeadless** [comment]
Hey! 
Thanks for brief explanation of a problem, this really helps to answer question or narrow down a problem.

What seems to happen, is array of Phones does not get converted to NSSet object. This should be done by EasyMapping automatically, to verify this behaviour, set breakpoint here:

https://github.com/lucasmedeirosleite/EasyMapping/blob/master/EasyMapping/EKPropertyHelper.m#L71-L93

This is where EasyMapping converts array of objects to what your NSManagedObject subclass expects. It should convert to NSSet based on your class, however something seems to go wrong.

Hope this helps.

**Comment by Chernomor1984** [comment]
It looks like 
objc_property_t property is nil

[https://gyazo.com/587fc72c207112c1fc54d654e1e3a1d1](url)

**Comment by DenHeadless** [comment]
Seems you did not set NSManagedObject class in your xcdatamodel file.
http://d.pr/i/PlOo

In EasyMapping example class is recognized:
http://d.pr/i/TUON

On your screenshot it is not, it assumes class is NSManagedObject:
http://d.pr/i/lUpI

**Comment by Chernomor1984** [comment]
Yep, you are absolutely right, dude!
 My apologies for wasting your time. 
I was careless when I studied your example. 

Thank you for your help and for your great lib!)

**Comment by DenHeadless** [comment]
Reporting problem with lot of details is half of the solution 🍺
