### ISSUE TITLE
Don't map property from NSManagedObject to Dictionary

### ISSUE THREAD

**Issue by drkdev** [lucasmedeirosleite/EasyMapping#144]
Is there a way of defining the mapping so a property or relationship won't map when converting to NSDictionary? I have some models with properties that sould not be mapped from object to dictionary, but they should be from dictionary to object.

I know with the methods whitValueBlock: reverseBlock it can be set to null, but is there a way to tell it to ignore the property completely?

**Comment by DenHeadless** [comment]
No, i don't think there's currently an API for this. Seems like withValueBlock:reverseBlock would be a way to do it right now.
