### ISSUE TITLE
Incorrect relationship serialization

### ISSUE THREAD

**Issue by ogubariev** [lucasmedeirosleite/EasyMapping#146]
In **EKSerializer** you have `+ (NSDictionary *)serializeObject:(id)object withMapping:(EKObjectMapping *)mapping` method. There are some bug in this method for serialization relationship. So, for simple propertyMappings you call `[self setValueOnRepresentation:representation fromObject:object withPropertyMapping:propertyMapping];` and all subPaths in it **propertyMapping.keyPath** are applied - it's correct. But for relationship you call `[representation setObject:someObject forKey:relationship.keyPath];` - and all subPaths are ignored. Can you fix it?
Thanks!

**Comment by DenHeadless** [comment]
Making PR would be a fastest way to get a fix done =)

**Comment by DenTelezhkin** [comment]
This issue is stale, if you want to pursue this functionality with EasyMapping, pull request is greatly appreciated.

Closing issue for now.
