### ISSUE TITLE
Crash in version 0.20.0: collectEntityNamesRecursively:mapping: 

### ISSUE THREAD

**Issue by Brusnikin** [lucasmedeirosleite/EasyMapping#149]
My exception point stop me here:

`EKManagedObjectMapping * mapping = (EKManagedObjectMapping *)[[oneMapping objectClass] objectMapping];`

with message:
> +[AvatarManagedObject objectMapping]: unrecognized selector sent to class 0x10041b958

I have a simple relationship with reverse connection one to one
<img width="374" alt="2017-02-12 20 15 28" src="https://cloud.githubusercontent.com/assets/10565354/22864459/0e1c61aa-f163-11e6-8012-c1959d5c17e3.png">

Now i'm in virsion 0.18.1

**Comment by DenHeadless** [comment]
Please take a look at [0.20.0 release](https://github.com/lucasmedeirosleite/EasyMapping/releases/tag/0.20.0) changes - there was a mapping resolver feature, that requires a little different handling of has one and has many mappings.

**Comment by armandzwan** [comment]
@Brusnikin How did you fix it?
