### ISSUE TITLE
EKSerializer

### ISSUE THREAD

**Issue by Brusnikin** [lucasmedeirosleite/EasyMapping#150]
I'm try to use serializeObject:withMapping:fromContext method and i have a crash here: `id returnedValue = [object valueForKeyPath:propertyMapping.property];` with message: 

> the entity ManagedPost is not key value coding-compliant for the key "content"

managedObject has a property "content" and plainObject to, but it's missing in json. Also i'm try to use this property ignoreMissingFields with flag YES, is it correct?

EasyMapping 2.0

**Comment by DenHeadless** [comment]
As i can remember, `ignoreMissingFields` property relates to EKMapper, not EKSerializer.

As for crash, it seems self-explanatory. For some reason, `ManagedPost` does not have `content` property. I would suggest checking your xcdatamodel, and verifying that object contains this property. Then you can try deleting app from the simulator/device and running again - sometimes CoreData on simulator holds old version of the model, and is not rebuild.

**Comment by Brusnikin** [comment]
> simulator holds old version of the model

it's true, thank you

**Comment by Brusnikin** [comment]
Denis, hi once again! Sorry that i'm writing personally, but i'm stuck! And
sorry for my english )

I have a provider, where i get EKManagedObjectMapping, but if i try like
this:

ManagedPost *post = (ManagedPost *)managedObject;

NSLog(@"%@", post.author); <--- has all properties and they are not nil!


    EKManagedObjectMapping *mapping = [_provider
mappingForManagedObjectClass:managedClass];



    NSDictionary *dictionary = [EKSerializer serializeObject:managedObject

                                                 withMapping:mapping

                                                 fromContext:_context];


dictionary has PlainPost and PlainAuthor, but PlainAuthor is empty
dictionary...


could you explain what i'm doing wrong?


PS

Thx for EasyMapping! )

2017-02-23 0:42 GMT+03:00 Denys Telezhkin <notifications@github.com>:

**Comment by DenHeadless** [comment]
Can you post code, that creates EKManagedObjectMapping? Maybe author is not mapped via relationship and is mapped via value block without reverse-block? Hard to tell without seeing the code.

**Comment by Brusnikin** [comment]
Hi! Tonight i'm install 0.18.1 version and it's OK! Versions
0.20.0/0.20.1 without success...


*MappingProvider*


- (EKManagedObjectMapping *)ManagedPostMapping

{

    NSDictionary *properties = @{@"id" :
NSStringFromSelector(@selector(post_id)),

                                 @"source" :
NSStringFromSelector(@selector(source)),

                                 @"title" :
NSStringFromSelector(@selector(title)),

                                 @"event_date" :
NSStringFromSelector(@selector(event_date)),

                                 @"content" :
NSStringFromSelector(@selector(content)),

                                 @"picture" :
NSStringFromSelector(@selector(picture))};



    return [EKManagedObjectMapping
mappingForEntityName:NSStringFromClass([ManagedPost class])


withBlock:^(EKManagedObjectMapping *mapping)

            {

                mapping.ignoreMissingFields = YES;



                [mapping mapPropertiesFromDictionary:properties];


                [mapping hasOne:[ManagedAuthor class]

                     forKeyPath:@"author"

                    forProperty:@"author"

              withObjectMapping:[self ManagedAuthorMapping]];



                mapping.primaryKey = @"post_id";

            }];

}


- (EKManagedObjectMapping *)ManagedAuthorMapping

{

    NSDictionary *properties = @{@"id" :
NSStringFromSelector(@selector(author_id)),

                                 @"first_name" :
NSStringFromSelector(@selector(first_name)),

                                 @"last_name" :
NSStringFromSelector(@selector(last_name))};


    return [EKManagedObjectMapping
mappingForEntityName:NSStringFromClass([ManagedAuthor class])


withBlock:^(EKManagedObjectMapping *mapping)

            {

                mapping.ignoreMissingFields = YES;


                [mapping mapPropertiesFromDictionary:properties];



                mapping.primaryKey = @"author_id";

            }];

}




*ManagedAuthor* <EKManagedMappingProtocol>



+ (EKManagedObjectMapping *)objectMapping

{

    return [EKManagedObjectMapping
mappingForEntityName:NSStringFromClass([self class])


withBlock:^(EKManagedObjectMapping * _Nonnull mapping) {}];

}



*Ponsomizer*


- (id)convertManagedObject:(NSManagedObject <EKManagedMappingProtocol
>*)managedObject

{

    Class managedClass = [managedObject class];

    NSString *substring = [NSStringFromClass(managedClass)
substringFromIndex:@"Managed".length];

    Class plainClass = NSClassFromString([@"Plain" stringByAppendingString
:substring]);


//    ManagedPost *post = (ManagedPost *)managedObject;

//    NSLog(@"%@", post.author);



    EKManagedObjectMapping *mapping = [_provider
mappingForManagedObjectClass:managedClass];



    NSDictionary *dictionary = [EKSerializer serializeObject:managedObject

                                                 withMapping:(
EKManagedObjectMapping *)mapping

                                                 fromContext:_context];



// *dictionary has empty author*!!!


    return [EKMapper fillObject:[plainClass new]

     fromExternalRepresentation:dictionary

                    withMapping:[plainClass objectMapping]];

}


*PlainPost *<EKMappingProtocol>


+ (EKObjectMapping *)objectMapping

{

    return [EKObjectMapping mappingForClass:self

                                  withBlock:^(EKObjectMapping * _Nonnull
mapping)

            {

                mapping.ignoreMissingFields = YES;



                [mapping mapPropertiesFromDictionary:@{@"id" : @"postId",

                                                       @"title" : @"title",

                                                       @"source" : @"source"
,

                                                       @"event_date" :
@"eventDate",

                                                       @"content" :
@"content"}];



                [mapping mapKeyPath:@"picture"

                         toProperty:@"picture"

                     withValueBlock:[EKMappingBlocks urlMappingBlock]

                       reverseBlock:[EKMappingBlocks urlReverseMappingBlock
]];



                [mapping hasOne:[PlainAuthor class]

                     forKeyPath:@"author"

                    forProperty:@"author"

              withObjectMapping:[PlainAuthor objectMapping]];

            }];

}


*PlainAuthor *<EKMappingProtocol>


+ (EKObjectMapping *)objectMapping

{

    return [EKObjectMapping mappingForClass:self

                                  withBlock:^(EKObjectMapping * _Nonnull
mapping)

            {

                [mapping mapPropertiesFromDictionary:@{@"author_id" :
@"authorId",

                                                       @"first_name" :
@"firstName",

                                                       @"last_name" :
@"lastName"}];

            }];

}

2017-02-23 10:43 GMT+03:00 Denys Telezhkin <notifications@github.com>:

**Comment by DenHeadless** [comment]
It's very hard to read code when it's formatted this way, however it seems that your author mapping is empty - ManagedAuthor <EKManagedMappingProtocol> objectMapping method returns empty mapping, which is why author is empty. I may be wrong, of course, but it's the first assumption I had while looking at this.

**Comment by Brusnikin** [comment]
ManagedAuthorObjectMapping is not empty! I'm test it on 0.18.1 version

Inside your method:

+(NSDictionary *)serializeObject:(id)object withMapping:(
EKManagedObjectMapping *)mapping fromContext:(NSManagedObjectContext
*)context

{

    NSMutableDictionary *representation = [NSMutableDictionary dictionary];


    //*mapping.propertyMappings - EMPTY!*


    [mapping.propertyMappings enumerateKeysAndObjectsUsingBlock:^(id key,
EKPropertyMapping *propertyMapping, BOOL *stop) {

        [self setValueOnRepresentation:representation

                     fromManagedObject:object

                   withPropertyMapping:propertyMapping

                             inContext:context];

    }];

2017-02-23 14:57 GMT+03:00 Denys Telezhkin <notifications@github.com>:

**Comment by Brusnikin** [comment]
2017-02-23 14:57 GMT+03:00 Denys Telezhkin <notifications@github.com>:

**Comment by DenHeadless** [comment]
I meant this code, that you sent:

```swift
+ (EKManagedObjectMapping *)objectMapping
{
    return [EKManagedObjectMapping
mappingForEntityName:NSStringFromClass([self class])
withBlock:^(EKManagedObjectMapping * _Nonnull mapping) {}];
}
```

Or it has something inside? I'm not sure I understand.
