### ISSUE TITLE
Recursive relationship to same object

### ISSUE THREAD

**Issue by jcavar** [lucasmedeirosleite/EasyMapping#151]
Hi,
We have the following JSON structure:

```
{
    "chat": 
    {
        "identifier": 1,
        "message": 
        {
            "identifier": 2,
            "chat": 
            {
                "identifier": 1
            }
        }
    }
}
```

We are using CoreData and we encountered problem when transforming this. Chat with identifier 1 is created twice. I think we identified why is this happening:

So the issue is in `EKManagedObjectMapper.m` `objectFromExternalRepresentation`. If object is not in cache, it is inserted and then filled from external representation. When filling it, inner chat is encountered and not found in cache and inserted as well. So we end up with 2 same chats.

The issue could be solved by caching object before calling `fillObject`. The problem is that primaryKey is not yet set to object so it can't be cached yet. This can be workarounded by getting primaryKey from external representation and caching it.

I hope this makes sense? Is this something that EasyMapping should handle?

**Comment by jcavar** [comment]
So implementation of cache would look something like this I think:
```
-(void)cacheObject:(NSManagedObject *)object
       withMapping:(EKManagedObjectMapping *)mapping
       externalRep:(NSDictionary *)representation
{
    if(!mapping.primaryKey) return;

    NSString *key = [object valueForKey:mapping.primaryKey];
    if (!key) {
        key = representation[mapping.primaryKeyPropertyMapping.keyPath];
    }
    NSMutableDictionary *entityObjectsMap = self.fetchedExistingEntities[mapping.entityName];
    entityObjectsMap[key] = object;
    self.fetchedExistingEntities[mapping.entityName] = entityObjectsMap;
}
```

**Comment by jcavar** [comment]
Or actually cache implementation doesn't need to change. We can just set primaryKey before adding object to cache.
Something like this:
```
    id primaryKey = externalRepresentation[mapping.primaryKeyPropertyMapping.keyPath];
    if (mapping.primaryKeyPropertyMapping.managedValueBlock) {
        primaryKey = mapping.primaryKeyPropertyMapping.managedValueBlock(mapping.primaryKeyPropertyMapping.keyPath, o, self.importer.context);
    }
    [object setValue:primaryKey forKey:mapping.primaryKey];
    [self.importer cacheObject:object withMapping:mapping];
    NSManagedObject * filledObject = [self fillObject:object
                           fromExternalRepresentation:externalRepresentation
                                          withMapping:mapping];    
    return filledObject;
```

**Comment by DenHeadless** [comment]
If you could drop a pull request with unit test for this, this would be really great. Recursive mappings are hard =)

**Comment by jcavar** [comment]
Hi, we filed the same issue on https://github.com/Yalantis/FastEasyMapping/issues/81, and they plan to fix it. Since implementation is very similar it may solve issue here as well.

**Comment by jcavar** [comment]
Hey @DenHeadless, thanks for resolving this. However, it seems that my initial solution was not so nice and FastEasyMapping did it in nicer way. See:
https://github.com/Yalantis/FastEasyMapping/pull/82/commits/6a13ef6f2da9231d271f7cd71029c6504fd66fe9

They split `fillObject` method in `fillAttributes` and `fillRelationships`. Then `fillAttribute`s can be safely called before caching and object is cached after it and before `fillRelationships`.

I find this nicer then extracting primary key from dictionary and I wanted to post PR for this, but didn't have time. If you are up for it I can do this when I find some time?

**Comment by DenHeadless** [comment]
Sure! I'm not making release right now, just added a test and a quick fix for this.

I want to do some more gardening work for the library when i have time, probably near April 20-21, and release a new version.

If you'll be able to find some time to clean up this prior to this date, this would be great.

**Comment by jcavar** [comment]
Yes, that sounds reasonable.
