### ISSUE TITLE
Required properties for object to be initialized.

### ISSUE THREAD

**Issue by nemissm** [lucasmedeirosleite/EasyMapping#157]
Assume that in described example object "Phone" must have nonnull property "number" to be valid. If we got server response without "number" we don't want to create non-valid "Phone" instance and assign it to "phones" array of "Person". Is it possible to return nil object if some condition fails?

**Comment by DenHeadless** [comment]
Hey!

That is an interesting question, but it has more question undercover. For example, do you want to fail entire Person object creation if phone is invalid? Or do you want to truncate "bad" phone records? 

We have partial solution for second, each EKObjectMapping has `mappingResolver` property, that allows you to choose, what mapping do you want to have for object. It does not allow to truncate bad records, but it does allow switching between different mappings to create different objects(https://github.com/lucasmedeirosleite/EasyMapping/blob/master/Tests/EasyMappingTests/EKRelationshipMappingTestCase.swift#L42-L52). 

Also you could use mapping with value block, and use `EKMapper.collectionOfObjects`, and filter them inside mapping block. 

But returning nil if condition fails unfortunately is not supported for now, though we might implement this in the future, if this feature is useful. It's hard to tell. What do you think, are two solutions I provided sufficient in your use case?

**Comment by DenTelezhkin** [comment]
This issue is stale, if you want to pursue this functionality with EasyMapping, pull request is greatly appreciated.

Closing issue for now.
