### ISSUE TITLE
WatchOS, Watch Extension

### ISSUE THREAD

**Issue by andreyoshev** [lucasmedeirosleite/EasyMapping#158]
Does this pod compatible with **WatchOS**? 

> The platform of the target `Watch Extension` (watchOS 2.0) is not compatible with `EasyMapping (0.21.2)`, which does not support `watchos`.

**Comment by DenHeadless** [comment]
We do support watchOS, not sure about this error message you are getting. We have somewhat wonky CocoaPods setup due to several podspecs, you can check it out here:

https://github.com/lucasmedeirosleite/EasyMapping/blob/master/EasyMapping.podspec#L17

What version of CocoaPods are you using?

**Comment by andreyoshev** [comment]
@DenHeadless this for replay. I'm using the last version of cocoapods - 1.3.1.

Works with watch:
spec.ios.deployment_target = '8.0'
spec.osx.deployment_target = '10.9'
spec.tvos.deployment_target = '9.0'
spec.watchos.deployment_target = '2.0'

Doesnt work with watch: 
s.ios.deployment_target = '8.0'
s.osx.deployment_target = '10.9'
s.tvos.deployment_target = '9.0'

**Comment by DenHeadless** [comment]
Last time i tried to submit with spec.watchos.deployment_target, CocoaPods failed lint for XCTest target, which is why this funky setup was created, and i was under the impression that it worked, at least for CocoaPods 1.0.0.

I will try to come up with a better podspec.

**Comment by DenHeadless** [comment]
@andreyoshev  Are you saying you installed EasyMapping/Core podspec explicitly and it worked?

**Comment by andreyoshev** [comment]
@DenHeadless I said I installed FasyEasyMapping where It works, but I like this framework more.
You can compare podspecs.

**Comment by andreyoshev** [comment]
I'll try to update podspec.

**Comment by DenTelezhkin** [comment]
This issue is stale, if you still have problems with installing EasyMapping on watchOS, i would recommend trying to use `EasyMapping/Core` in Podfile. At least [json podspec representation](https://github.com/CocoaPods/Specs/blob/master/Specs/8/4/4/EasyMapping/0.23.0/EasyMapping.podspec.json#L24-L33) seems to think that watchOS is supported.

Closing issue for now.
