### ISSUE TITLE
Mapping in serializedObjectInContext ?

### ISSUE THREAD

**Issue by armandzwan** [lucasmedeirosleite/EasyMapping#161]
Why does
- (NSDictionary *)serializedObjectInContext:(NSManagedObjectContext *)context;

Not have a mapping? like:

- (NSDictionary *)serializedObjectInContext:(NSManagedObjectContext *)context withMapping:(EKManagedObjectMapping*)mapping;

**Comment by DenHeadless** [comment]
Mostly for convenience and because of recursive mappings, that would have no idea where to take mapping from, I believe.

You can use 

```
EKSerializer.serializeObject(_:withMapping:fromContext:)
```

to get what you need.

https://github.com/lucasmedeirosleite/EasyMapping/blob/master/Sources/EasyMapping/EKSerializer.h#L69

**Comment by armandzwan** [comment]
Thanks. That was exactly what I needed.
