### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by armandzwan** [lucasmedeirosleite/EasyMapping#163]
Is this Repo being maintained, or is the project dead?
I am not receiving any replies on my open issue since October...

**Comment by DenHeadless** [comment]
Hi!

Project is maintained, but is not being actively developed. If you have ideas or improvements you want to bring to the framework, PR are always welcomed. But digging into specific issues is too time-consuming for maintainers at the moment, unfortunately. 

If you found a bug, that needs to be fixed, the easiest thing to do is get a test, that checks for it, even if it's failing. Our test suite is quite comprehensive and covers almost 100% of framework functionality.
