### ISSUE TITLE
Unnecessary required protocol?

### ISSUE THREAD

**Issue by sebastianludwig** [lucasmedeirosleite/EasyMapping#164]
Commit 229d2fa added `<EKManagedMappingProtocol>` to the object parameter and the return type of `+fillObject:fromExternalRepresentation:withMapping:inManagedObjectContext:` (and a few others). However I don't see that `+objectMapping` is actually called on the `objectClass`. This becomes an issue (Xcode warning) if the object being filled does not conform to `EKManagedMappingProtocol` because the same object is filled from two different sources with two different mappings and therefore can't implement `+objectMapping` in a meaningful way.

Is there a place I'm currently missing where the protocol conformance is required? If not, would you be willing to review, discuss and accept a PR changing the fact?

**Comment by DenHeadless** [comment]
Hi there!

I agree, in several places those constraints are unnecessary. They were meant to provide better interoperability with Swift, and some of changes in that commit do, but definitely not the one you mention, cause indeed there are several places where this is not required.

Please open PR if you need that, i'll review, merge it, and cut a new release.
