### ISSUE TITLE
Is there an equivalent to Mantle's +classForParsingJSONDictionary: for deserializing class clusters?

### ISSUE THREAD

**Issue by Apocryphon** [lucasmedeirosleite/EasyMapping#166]
Mantle has a neat protocol method to determine which specific object mapper/parser should be used at runtime for class clusters: [+classForParsingJSONDictionary](https://github.com/Mantle/Mantle). This method allows the user to specify which object mapping to use when working with different subclasses. Is there a way to do something similar in EasyMapping?

**Comment by DenHeadless** [comment]
Yep! It shipped in 0.20.0 release:

https://github.com/lucasmedeirosleite/EasyMapping/releases/tag/0.20.0

Is this what you are looking for?

**Comment by Apocryphon** [comment]
Similar, but not exactly. It'd be nice to be able to do that not in the context of determining the type of an object in a relationship mapping, but the actual object being deserialized. As in the example from the Mantle homepage, you're deserializing dictionaries that are similar but contain specific keys that distinguish from other ones. When you find those keys, then `objectFromExternalRepresentation:withMapping:` can be called.

**Comment by DenTelezhkin** [comment]
This issue is stale, if you want to pursue this functionality with EasyMapping, pull request is greatly appreciated.

Closing issue for now.
